kind: pipeline
name: default
type: docker

steps:
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: build
  image: gcc
  commands:
  - make clean && make
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
